### ISSUE TITLE
Messaging Module: Template Updates: Yukon Grant - INSTITUTION

### ISSUE THREAD

**Issue by klondikemarlen** [icefoganalytics/sfa-client#44]
Relates to https://github.com/icefoganalytics/sfa-client/issues/3

# Context

Update email templates used in https://github.com/icefoganalytics/sfa-client/issues/1 with production versions.
See https://github.com/icefoganalytics/sfa-client/pull/10 for example.

Translate "Yukon Grant - INSTITUTION.docx" into an html/pdf template and serve it up via the appropriate endpoint.

**Comment by datajohnson** [comment]
Have you ever had a single button click download two files? Like the interface makes a single endpoint request but the API responds with two downloads? In this case the student letter and the institution letter

**Comment by klondikemarlen** [comment]
I have not, but I did some research and it seems there are two paths.
a. make a zip of both files and return that. This seems to be the most standard and least flaky approach
b. On button click, create multiple <a> tags with download links to the appropriate files, then programmatically trigger a click on each virtual link. This seems like a clever hack, but apparently it gets block by popup blockers and the like, so it can be kind of a flaky experience.

**Comment by datajohnson** [comment]
<img width="954" alt="image" src="https://github.com/icefoganalytics/sfa-client/assets/346325/ff05a2c3-3d89-4364-a302-f18f1c0a41e6">

**Comment by klondikemarlen** [comment]
Fixed in https://github.com/icefoganalytics/sfa-client/pull/45
