### ISSUE TITLE
Messaging Module: Template Updates: YG Rejection Letter

### ISSUE THREAD

**Issue by klondikemarlen** [icefoganalytics/sfa-client#48]
Relates to https://github.com/icefoganalytics/sfa-client/issues/3

# Context

Update email templates used in https://github.com/icefoganalytics/sfa-client/issues/1 with production versions.
See https://github.com/icefoganalytics/sfa-client/pull/10 for example.

Translate "YG Rejection Letter.docx" into an html/pdf template and serve it up via the appropriate endpoint.

**Comment by datajohnson** [comment]
Is this still blocked? Did you find the rejection status?

**Comment by klondikemarlen** [comment]
Oh, yeah, I've been setting the issue as blocked, waiting on the PR to be merged? I'm not sure if it makes sense, but I wasn't sure what status to put the ticket in, once the PR was ready for review.
